---
- name: NETWORK-DEVICES UPTIME
  hosts: all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
    - name: username
      prompts: Junos Username
      private: no


    - name: password
      prompts: Junos Password
      private: yes


  tasks:
    - name: Single "show version" command.
      juniper_junos_command:
        commands: "show version"
        provider:
          host: "{{ ansible_host }}"
          port: 22
          user: "{{ username }}"
          password: "{{ password }}"
      register: uptime
    - name: display uptimes
      debug:
        var: uptime.stdout_lines

    - name: Single three commands.
      juniper_junos_command:
        commands:
          - "show version"
          - "show system uptime"
          - "show interface terse"
        provider:
          host: "{{ ansible_host }}"
          port: 22
          user: "{{ username }}"
          password: "{{ password }}"
      register: uptime
    - name: display uptimes
      debug:
        var: uptime

    - name: get uptime using galaxy module
      juniper_junos_command:
        commands:
          - show system uptime
          - show chassis hardware detail
        provider:
          host: "{{ ansible_host }}"
          port: 22
          user: "{{ username }}"
          password: "{{ password }}"
      register: uptime
    - name: display uptimes
      debug:
        var: uptime






